name: Checkout and display submodules
on: [push, pull_request]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VOGSPHERE_SSH_KEY }}" > ~/.ssh/id_rsa_vogsphere
          echo "${{ secrets.MY_GITHUB_SSH_KEY }}" > ~/.ssh/github_action_key
          chmod 600 ~/.ssh/id_rsa_vogsphere ~/.ssh/github_action_key

      - name: Configure SSH for Vogsphere
        run: |
          echo "Host vogsphere.42paris.fr" >> ~/.ssh/config
          echo "  HostName vogsphere.42paris.fr" >> ~/.ssh/config
          echo "  User git" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa_vogsphere" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Configure SSH for GitHub
        run: |
          echo "Host github.com" >> ~/.ssh/config
          echo "  User git" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/github_action_key" >> ~/.ssh/config
          echo "  StrictHostKeyChecking accept-new" >> ~/.ssh/config

      - name: Fix SSH Key Permissions 🔧
        run: chmod 400 ~/.ssh/github_action_key

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.GITHUB_SSH_KEY }}

      - name: Copy submodule files to main repo
        run: |
          mkdir -p Projects/libft_125_mirror
          rsync -av --progress Projects/libft_125/ Projects/libft_125_mirror/

      - name: Remove Git metadata from copied submodule
        run: rm -rf Projects/libft_125_mirror/.git

      - name: Commit and push updated submodule content
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin git@github.com:M1000-93/Cursus_2023.git
          git add Projects/libft_125_mirror/
          git commit -m "Sync submodule content for visibility on GitHub" || echo "No changes to commit"
          git push origin HEAD:main_cursus_2023
